# Generated by Django 2.0.7 on 2018-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='percentage_safe',
            field=models.IntegerField(blank=True),
        ),
    ]
